version: '3.8'

services:
  event-finder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0