version: '3.8'

services:
  event-finder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1